// <auto-generated />
namespace MinhaCelula.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fifth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fifth));
        
        string IMigrationMetadata.Id
        {
            get { return "201909291713421_fifth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
